flowchart TD
    Start([Início])
    Step1[Navegou para https://homologacao.axhub.axion.ws/Home/Login?ReturnUrl=https%3A%2F%2Fhomologacao.axhub.axion.ws%2Fnao-autorizado]
    Start --> Step1
    Step2[Clicou em "#Username"]
    Step1 --> Step2
    Step3[Preencheu campo #Username]
    Step2 --> Step3
    Step4[Preencheu campo #Username]
    Step3 --> Step4
    Step5[Preencheu campo #Username]
    Step4 --> Step5
    Step6[Preencheu campo #Password]
    Step5 --> Step6
    Step7[Preencheu campo #Password]
    Step6 --> Step7
    Step8[Preencheu campo #Password]
    Step7 --> Step8
    Step9[Preencheu campo #Password]
    Step8 --> Step9
    Step10[Preencheu campo #Password]
    Step9 --> Step10
    Step11[Preencheu campo #Password]
    Step10 --> Step11
    Step12[Preencheu campo #Password]
    Step11 --> Step12
    Step13[Navegou para https://homologacao.axhub.axion.ws/nao-autorizado]
    Step12 --> Step13
    Step14[Navegou para https://homologacao.axhub.axion.ws/]
    Step13 --> Step14
    Step15[Clicou em "×"]
    Step14 --> Step15
    Step16[Clicou em "Cronotacógrafo"]
    Step15 --> Step16
    Step17[Navegou para https://homologacao.axhub.axion.ws/cronotacografo]
    Step16 --> Step17
    Step18[Clicou em "#dataHoraInicio"]
    Step17 --> Step18
    Step19[Clicou em "9"]
    Step18 --> Step19
    Step20[Preencheu campo #dataHoraInicio]
    Step19 --> Step20
    Step21[Clicou em "Mais Filtros"]
    Step20 --> Step21
    Step22[Clicou em " Filtrar"]
    Step21 --> Step22
    Step23[Clicou em " Limpar"]
    Step22 --> Step23
    Step24[Preencheu campo #dataHoraFim]
    Step23 --> Step24
    Step25[Clicou em "#dataHoraInicio"]
    Step24 --> Step25
    Step26[Clicou em "2"]
    Step25 --> Step26
    Step27[Preencheu campo #dataHoraInicio]
    Step26 --> Step27
    Step28[Preencheu campo ]
    Step27 --> Step28
    Step29[Clicou em "2"]
    Step28 --> Step29
    Step30[Preencheu campo #dataHoraInicio]
    Step29 --> Step30
    Step31[Clicou em " Filtrar"]
    Step30 --> Step31
    Step32[Clicou em "Mais Filtros"]
    Step31 --> Step32
    Step33[Clicou em "Relatórios"]
    Step32 --> Step33
    Step34[Navegou para https://homologacao.axhub.axion.ws/relatorio/relatorioeventoequipamento]
    Step33 --> Step34
    Step35[Clicou em "Buscar"]
    Step34 --> Step35
    Step36[Clicou em "OK"]
    Step35 --> Step36
    Step37[Clicou em "24"]
    Step36 --> Step37
    Step38[Clicou em "Todos os Grupos"]
    Step37 --> Step38
    Step39[Clicou em ".k-virtual-scrollable-wrap"]
    Step38 --> Step39
    Step40[Clicou em "Buscar"]
    Step39 --> Step40
    Step41[Clicou em "Operações"]
    Step40 --> Step41
    Step42[Navegou para https://homologacao.axhub.axion.ws/faixa]
    Step41 --> Step42
    Step43[Clicou em "T1021-1"]
    Step42 --> Step43
    Step44[Clicou em "Cronotacógrafo"]
    Step43 --> Step44
    Step45[Navegou para https://homologacao.axhub.axion.ws/consultacronotacografo]
    Step44 --> Step45
    Step45 --> End([Fim])
