<#
.SYNOPSIS
    Gera um novo projeto de documentacao Docusaurus para produtos Axion Tecnologia.

.DESCRIPTION
    Cria toda a estrutura de pastas, arquivos de configuracao, CSS, paginas iniciais
    e workflow de deploy seguindo o padrao definido no workspace Axion.Docs.

.PARAMETER NomeProjeto
    Nome do projeto (ex: AxVision). Sera usado como nome da pasta e no config.

.PARAMETER TituloProjeto
    Descricao curta do sistema (ex: Sistema de Videomonitoramento).

.PARAMETER CorPrimaria
    Cor primaria em hexadecimal (ex: #3498db). Padrao: #3498db

.PARAMETER Modulos
    Lista de modulos separados por virgula (ex: "Cameras,Alertas,Gravacoes").

.EXAMPLE
    .\novo-projeto-docs.ps1 -NomeProjeto "AxVision" -TituloProjeto "Sistema de Videomonitoramento" -Modulos "Cameras,Alertas,Gravacoes,Relatorios"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$NomeProjeto,

    [Parameter(Mandatory=$true)]
    [string]$TituloProjeto,

    [string]$CorPrimaria = "#3498db",

    [string]$Modulos = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$base = Join-Path $root "$NomeProjeto\docs-portal"

if (Test-Path $base) {
    Write-Error "Pasta $base ja existe. Abortando."
    return
}

Write-Host "Criando projeto: $NomeProjeto" -ForegroundColor Cyan
Write-Host "Local: $base" -ForegroundColor Gray

# Criar estrutura de pastas
$folders = @(
    "$NomeProjeto\Database"
    "$NomeProjeto\docs-portal\docs\img"
    "$NomeProjeto\docs-portal\docs\primeiros-passos"
    "$NomeProjeto\docs-portal\docs\glossario"
    "$NomeProjeto\docs-portal\src\css"
    "$NomeProjeto\docs-portal\static\img"
)

# Adicionar pastas de modulos
$modulosList = @()
if ($Modulos -ne "") {
    $modulosList = $Modulos -split "," | ForEach-Object { $_.Trim().ToLower() -replace "\s+", "-" }
    foreach ($mod in $modulosList) {
        $folders += "$NomeProjeto\docs-portal\docs\$mod"
    }
}

foreach ($f in $folders) {
    $fullPath = Join-Path $root $f
    New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
}

Write-Host "  Pastas criadas" -ForegroundColor Green

# --- docusaurus.config.ts ---
$footerModulos = ""
if ($modulosList.Count -gt 0) {
    $first = $modulosList[0]
    $footerModulos = "            { label: '$($Modulos.Split(',')[0].Trim())', to: '/$first' },"
}

$configContent = @"
import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: '$NomeProjeto',
  tagline: 'Manual do Usuario - $TituloProjeto',
  favicon: 'img/favicon.ico',
  future: { v4: true },
  url: 'https://axion-tecnologia.github.io',
  baseUrl: '/$NomeProjeto.Docs/',
  organizationName: 'Axion-Tecnologia',
  projectName: '$NomeProjeto.Docs',
  onBrokenLinks: 'warn',
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
      onBrokenMarkdownImages: 'warn',
    },
  },
  i18n: { defaultLocale: 'pt-BR', locales: ['pt-BR'] },
  presets: [
    [
      'classic',
      {
        docs: { sidebarPath: './sidebars.ts', routeBasePath: '/' },
        blog: false,
        theme: { customCss: './src/css/custom.css' },
      } satisfies Preset.Options,
    ],
  ],
  themeConfig: {
    colorMode: { defaultMode: 'light', respectPrefersColorScheme: true },
    navbar: {
      title: '$NomeProjeto',
      logo: { alt: '$NomeProjeto Logo', src: 'img/logo.png' },
      items: [
        { type: 'docSidebar', sidebarId: 'manualSidebar', position: 'left', label: 'Manual do Usuario' },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentacao',
          items: [
            { label: 'Inicio', to: '/' },
            { label: 'Primeiros Passos', to: '/primeiros-passos/login' },
          ],
        },
        {
          title: 'Modulos',
          items: [
$footerModulos
          ],
        },
        {
          title: 'Axion Tecnologia',
          items: [{ label: 'Site Axion', href: 'https://axiontecnologia.com.br/' }],
        },
      ],
      copyright: ``Copyright `${"$"}{new Date().getFullYear()} Axion Tecnologia. Todos os direitos reservados.``,
    },
    prism: { theme: prismThemes.github, darkTheme: prismThemes.dracula },
  } satisfies Preset.ThemeConfig,
};

export default config;
"@
[System.IO.File]::WriteAllText("$base\docusaurus.config.ts", $configContent, [System.Text.UTF8Encoding]::new($false))

# --- sidebars.ts ---
$sidebarsContent = @"
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  manualSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
"@
[System.IO.File]::WriteAllText("$base\sidebars.ts", $sidebarsContent, [System.Text.UTF8Encoding]::new($false))

# --- package.json ---
$slug = $NomeProjeto.ToLower() -replace "[^a-z0-9]", "-"
$packageContent = @"
{
  "name": "axion-$slug-docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@docusaurus/core": "3.9.2",
    "@docusaurus/preset-classic": "3.9.2",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@docusaurus/module-type-aliases": "3.9.2",
    "@docusaurus/tsconfig": "3.9.2",
    "@docusaurus/types": "3.9.2",
    "typescript": "~5.6.2"
  },
  "engines": { "node": ">=20.0" }
}
"@
[System.IO.File]::WriteAllText("$base\package.json", $packageContent, [System.Text.UTF8Encoding]::new($false))

# --- tsconfig.json ---
$tsconfigContent = @"
{
  "extends": "@docusaurus/tsconfig",
  "compilerOptions": { "baseUrl": "." }
}
"@
[System.IO.File]::WriteAllText("$base\tsconfig.json", $tsconfigContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "  Configs criados" -ForegroundColor Green

# --- custom.css ---
$cssContent = @"
:root {
  --ifm-color-primary: $CorPrimaria;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
  --ifm-navbar-background-color: #2c3e50;
  --ifm-navbar-link-color: #ecf0f1;
  --ifm-menu-color: #2c3e50;
  --ifm-menu-color-active: $CorPrimaria;
  --ifm-link-color: $CorPrimaria;
  --ifm-footer-background-color: #2c3e50;
  --ifm-footer-color: #ecf0f1;
  --ifm-font-family-base: 'Segoe UI', system-ui, -apple-system, sans-serif;
}

[data-theme='dark'] {
  --ifm-navbar-background-color: #1a252f;
  --ifm-footer-background-color: #1a252f;
}

.navbar { box-shadow: 0 1px 4px rgba(0, 0, 0, 0.15); }
.navbar__title { color: #ecf0f1; font-weight: 700; font-size: 1.25rem; }

.menu__link--active:not(.menu__link--sublist) {
  border-left: 3px solid $CorPrimaria;
  padding-left: calc(var(--ifm-menu-link-padding-horizontal) - 3px);
}

table th {
  font-weight: 600;
  border-bottom: 2px solid $CorPrimaria;
}

img[alt*="Tela"] {
  border: 1px solid #d5dbdb;
  border-radius: 6px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin: 1rem 0;
}
"@
[System.IO.File]::WriteAllText("$base\src\css\custom.css", $cssContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "  CSS criado" -ForegroundColor Green

# --- intro.md ---
$moduloRows = ""
$pos = 2
foreach ($mod in $modulosList) {
    $label = (Get-Culture).TextInfo.ToTitleCase(($mod -replace "-", " "))
    $moduloRows += "| $pos | [$label](./$mod/) | - |`n"
    $pos++
}

$introContent = @"
---
sidebar_position: 1
slug: /
title: Visao Geral
---

# $NomeProjeto - Manual do Usuario

Bem-vindo ao manual do **$NomeProjeto**, $TituloProjeto desenvolvido pela **Axion Tecnologia**.

## Modulos do Sistema

| # | Modulo | Descricao |
|---|--------|-----------|
| 1 | [Primeiros Passos](./primeiros-passos/login) | Login, navegacao e dashboard |
$moduloRows
## Como usar este manual

Use o **menu lateral** para navegar entre os modulos. Cada secao contem:

- **Como acessar** - caminho no menu do sistema
- **Campos exibidos** - detalhamento de cada campo da tela
- **Filtros disponiveis** - opcoes de pesquisa e filtragem
"@
[System.IO.File]::WriteAllText("$base\docs\intro.md", $introContent, [System.Text.UTF8Encoding]::new($false))

# --- primeiros-passos ---
$catPP = '{"label": "Primeiros Passos", "position": 2, "collapsible": true, "collapsed": false}'
[System.IO.File]::WriteAllText("$base\docs\primeiros-passos\_category_.json", $catPP, [System.Text.UTF8Encoding]::new($false))

$loginContent = @"
---
sidebar_position: 1
title: Login
description: Como acessar o sistema $NomeProjeto
---

# Login

Tela de autenticacao do $NomeProjeto. Todos os usuarios precisam se autenticar com login e senha.

## Acessando o sistema

1. Abra o navegador e acesse o endereco do $NomeProjeto
2. Informe seu **Login**
3. Informe sua **Senha**
4. Clique em **Entrar**

## Recuperacao de senha

1. Na tela de login clique em **Esqueci minha senha**
2. Informe o e-mail cadastrado
3. Acesse sua caixa de entrada e clique no link de redefinicao
4. Defina uma nova senha e confirme
"@
[System.IO.File]::WriteAllText("$base\docs\primeiros-passos\login.md", $loginContent, [System.Text.UTF8Encoding]::new($false))

$dashContent = @"
---
sidebar_position: 2
title: Dashboard
description: Painel principal do sistema $NomeProjeto
---

# Dashboard

Tela principal exibida apos o login. Apresenta indicadores e atalhos para os modulos do sistema.

## Como Acessar

O dashboard e exibido automaticamente apos o login.
"@
[System.IO.File]::WriteAllText("$base\docs\primeiros-passos\dashboard.md", $dashContent, [System.Text.UTF8Encoding]::new($false))

$navContent = @"
---
sidebar_position: 3
title: Navegacao
description: Como navegar pelo sistema $NomeProjeto
---

# Navegacao

O $NomeProjeto utiliza menu lateral para acesso aos modulos.

## Menu Lateral

O menu lateral esquerdo exibe todos os modulos disponiveis. Clique em um modulo para expandir seus submenus.

## Barra Superior

A barra superior exibe o nome do usuario logado e opcoes de configuracao.
"@
[System.IO.File]::WriteAllText("$base\docs\primeiros-passos\navegacao.md", $navContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "  Primeiros Passos criados" -ForegroundColor Green

# --- Modulos ---
$position = 3
foreach ($mod in $modulosList) {
    $label = (Get-Culture).TextInfo.ToTitleCase(($mod -replace "-", " "))
    $catJson = "{`"label`": `"$label`", `"position`": $position, `"collapsible`": true, `"collapsed`": true}"
    [System.IO.File]::WriteAllText("$base\docs\$mod\_category_.json", $catJson, [System.Text.UTF8Encoding]::new($false))

    $indexContent = @"
---
sidebar_position: 1
title: $label
description: Modulo $label do $NomeProjeto
---

# $label

Descricao do modulo $label.

## Como Acessar

**Menu lateral** > **$label**
"@
    $fileName = if ($mod -match "-") { $mod } else { $mod }
    [System.IO.File]::WriteAllText("$base\docs\$mod\$fileName.md", $indexContent, [System.Text.UTF8Encoding]::new($false))

    $position++
}

if ($modulosList.Count -gt 0) {
    Write-Host "  $($modulosList.Count) modulos criados" -ForegroundColor Green
}

# --- Glossario ---
$glossarioPosition = $position
$catGlossario = @"
{
  "label": "Glossario Tecnico",
  "position": $glossarioPosition,
  "collapsed": false,
  "link": {
    "type": "generated-index",
    "description": "Termos tecnicos utilizados no sistema $NomeProjeto."
  }
}
"@
[System.IO.File]::WriteAllText("$base\docs\glossario\_category_.json", $catGlossario, [System.Text.UTF8Encoding]::new($false))
Write-Host "  Glossario criado" -ForegroundColor Green

# --- Database SQL placeholder ---
$sqlContent = "-- Schema do banco de dados $NomeProjeto`n-- Gerado automaticamente`n"
[System.IO.File]::WriteAllText((Join-Path $root "$NomeProjeto\Database\$NomeProjeto.sql"), $sqlContent, [System.Text.UTF8Encoding]::new($false))

# --- GitHub Actions Workflow ---
$workflowDir = Join-Path $root ".github\workflows"
if (-not (Test-Path $workflowDir)) {
    New-Item -ItemType Directory -Path $workflowDir -Force | Out-Null
}

$nomeLower = $NomeProjeto.ToLower()
$workflowContent = @"
name: Deploy $NomeProjeto Docs to GitHub Pages

on:
  push:
    branches: [main]
    paths: ['$NomeProjeto/docs-portal/**']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-$nomeLower"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $NomeProjeto/docs-portal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: $NomeProjeto/docs-portal/package-lock.json
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: $NomeProjeto/docs-portal/build

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"@
[System.IO.File]::WriteAllText("$workflowDir\deploy-$nomeLower-docs.yml", $workflowContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "  Workflow criado" -ForegroundColor Green

# --- Resumo ---
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Projeto $NomeProjeto criado com sucesso!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Proximos passos:" -ForegroundColor Yellow
Write-Host "  cd $NomeProjeto\docs-portal"
Write-Host "  npm install"
Write-Host "  npm run start"
Write-Host ""
